version: "3"

services:
    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - ./.data/redis:/data
    server:
        build: .docker/node
        ports:
            - 3000:3000
        volumes:
            - ./server:/src
    # frontend:
    #     image: nginx
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./frontend/build:/usr/share/nginx/html
